[project]
description = "A simple ecies demo based on FastAPI"
name = "eciespy-demo"
version = "0.1.0"

readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "eciespy>=0.4.2",
  "fastapi>=0.114.2",
  "python-multipart>=0.0.9",
  "uvicorn>=0.30.6",
  "uvloop>=0.20.0",
]

[tool.uv]
dev-dependencies = [
  "mypy>=1.11.2",
  "ruff>=0.6.5",
]
