[tool.poetry]
authors = ["Weiliang Li <to.be.impressive@gmail.com>"]
description = ""
license = "MIT"
name = "eciespy-demo"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"

eciespy = "^0.4.2"
# server
fastapi = "^0.110.3"
python-multipart = "^0.0.6"
uvicorn = "^0.22.0"
uvloop = "^0.17.0"

[tool.poetry.dev-dependencies]
black = "^23.3"
flake8 = "^6.0.0"
mypy = "^1.4.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
