[tool.poetry]
name = "eciespy-demo"
version = "0.1.0"
description = ""
authors = ["Weiliang Li <to.be.impressive@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.61.1"
python-multipart = "^0.0.5"
eciespy = "^0.3.7"
uvicorn = "^0.11.8"


[tool.poetry.dev-dependencies]
mypy = "^0.782"
flake8 = "^3.8.3"
black = "^20.8b1"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
