[tool.poetry]
authors = ["Weiliang Li <to.be.impressive@gmail.com>"]
description = ""
license = "MIT"
name = "eciespy-demo"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"

eciespy = "^0.3.7"
# server
fastapi = "^0.85.1"
python-multipart = "^0.0.5"
uvicorn = "^0.19.0"
uvloop = "^0.17.0"

[tool.poetry.dev-dependencies]
black = "^22.10"
flake8 = "^5.0.4"
mypy = "^0.982"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
