[tool.poetry]
authors = ["Weiliang Li <to.be.impressive@gmail.com>"]
description = ""
license = "MIT"
name = "eciespy-demo"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"

eciespy = "^0.3.7"
# server
fastapi = "^0.70.0"
python-multipart = "^0.0.5"
uvicorn = "^0.15.0"
uvloop = "^0.16.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^4.0.1"
mypy = "^0.800"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
