[tool.poetry]
authors = ["Weiliang Li <to.be.impressive@gmail.com>"]
description = ""
license = "MIT"
name = "eciespy-demo"
package-mode = false
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"

eciespy = "^0.4.0"

# server
fastapi = "^0.111.0"
python-multipart = "^0.0.9"
uvicorn = "^0.30.4"
uvloop = "^0.19.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.1"
ruff = "^0.4.8"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
