name: CD

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install uv

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: uv export --no-dev --no-hashes --format requirements-txt > requirements.txt

      - uses: neobrains/space-pipe@v0.5
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          space_push: true
