name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry
      - run: pipx inject poetry poetry-plugin-export

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - run: poetry export -f requirements.txt -o requirements.txt --without=dev
      - run: poetry install
