name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install uv

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: uv export --no-dev --no-hashes --format requirements-txt > requirements.txt
      - run: uv sync
